apiVersion: v1
kind: Service
metadata:
  name: igvtools-app
spec:
  selector:
    app: igvtools-app
    env: dev
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
